from __future__ import annotations

import random
import os
from pathlib import Path
from typing import Any, Dict, Optional

import cv2
import numpy as np

try:
    from ultralytics import YOLO
except Exception:  # pragma: no cover - optional dependency fallback
    YOLO = None


MODEL_NAME = os.getenv("MODEL_NAME", "yolov8n.pt")
_MODEL = None


def _risk_from_confidence(detected: bool, object_name: str, confidence: float) -> str:
    """Translate model confidence into a simple risk label."""
    if not detected:
        return "low"
    if object_name in {"person", "intruder"} and confidence >= 0.85:
        return "high"
    if confidence >= 0.65:
        return "medium"
    return "low"


def _mock_result() -> Dict[str, Any]:
    """Return a lightweight fake result for demo or fallback scenarios."""
    detected = random.random() > 0.2
    object_name = random.choice(["person", "face", "bicycle", "vehicle", "unknown"]) if detected else "none"
    confidence = round(random.uniform(0.62, 0.98) if detected else random.uniform(0.0, 0.2), 2)
    return {
        "detected": detected,
        "object": object_name,
        "confidence": confidence,
        "risk_level": _risk_from_confidence(detected, object_name, confidence),
        "model_mode": "mock-ai",
        "notes": "Generated by fallback mock mode.",
    }


def _load_model():
    """Lazy-load YOLO so startup stays fast and errors are isolated."""
    global _MODEL
    if _MODEL is not None:
        return _MODEL
    if YOLO is None:
        return None
    try:
        _MODEL = YOLO(MODEL_NAME)
        return _MODEL
    except Exception:
        return None


def get_model_status() -> Dict[str, Any]:
    """Expose model readiness for the dashboard and integration checks."""
    model = _load_model()
    return {
        "model_name": MODEL_NAME,
        "ultralytics_available": YOLO is not None,
        "loaded": model is not None,
        "mode": "yolo" if model is not None else "mock-ai",
    }


def _decode_image(image_bytes: bytes):
    """Convert raw bytes into an OpenCV image."""
    arr = np.frombuffer(image_bytes, dtype=np.uint8)
    image = cv2.imdecode(arr, cv2.IMREAD_COLOR)
    if image is None:
        return None
    return image


def _run_yolo(image) -> Dict[str, Any]:
    """Run inference and map YOLO output into the app contract."""
    model = _load_model()
    if model is None:
        return _mock_result()

    try:
        results = model.predict(image, verbose=False)
        if not results:
            return {
                "detected": False,
                "object": "none",
                "confidence": 0.0,
                "risk_level": "low",
                "model_mode": "yolo-unavailable",
                "notes": "YOLO returned no result.",
            }

        boxes = results[0].boxes
        names = results[0].names or {}
        if boxes is None or len(boxes) == 0:
            return {
                "detected": False,
                "object": "none",
                "confidence": 0.0,
                "risk_level": "low",
                "model_mode": "yolo",
                "notes": "No object detected by YOLO.",
            }

        confidences = boxes.conf.cpu().numpy().tolist()
        classes = boxes.cls.cpu().numpy().astype(int).tolist()
        best_idx = int(np.argmax(confidences))
        best_conf = float(confidences[best_idx])
        best_class = classes[best_idx]
        object_name = names.get(best_class, str(best_class))
        detected = best_conf >= 0.25

        return {
            "detected": detected,
            "object": object_name,
            "confidence": best_conf,
            "risk_level": _risk_from_confidence(detected, object_name, best_conf),
            "model_mode": "yolo",
            "notes": f"YOLO model: {MODEL_NAME}",
        }
    except Exception as exc:
        return {
            "detected": False,
            "object": "none",
            "confidence": 0.0,
            "risk_level": "low",
            "model_mode": "yolo-error",
            "notes": f"YOLO inference failed: {exc}",
        }


def analyze_image(image_bytes: Optional[bytes], force_mock: bool = False) -> Dict[str, Any]:
    """Main analysis entrypoint used by the FastAPI layer."""
    if force_mock or not image_bytes:
        return _mock_result()

    image = _decode_image(image_bytes)
    if image is None:
        return _mock_result()

    return _run_yolo(image)
